### ISSUE TITLE
加载leafletCN包后叠加高德地图时显示leaflet()函数不存在

### ISSUE THREAD

**Issue by wushengzhong** [Lchiffon/leafletCN#5]
我加载了leafletCN包后调用如下函数

`leaflet() %>%
      amap() %>%  
      addMarkers(lng=121.48, lat=31.22, popup="企业天地")`

显示如下错误
> Error in leaflet() : could not find function "leaflet"

**请问是什么原因呢？**

**Comment by Lchiffon** [comment]
你再`library(leaflet)`试试

**Comment by wushengzhong** [comment]
原来如此 谢谢😂
